"""Add portfolio fields with email constraint fix

Revision ID: d0049b3b7c22
Revises: 6c73b95af0e2
Create Date: 2025-09-21 01:29:29.885416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0049b3b7c22'
down_revision = '6c73b95af0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('removed_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('removed_user')
    # ### end Alembic commands ###
